# Generated by Django 2.2 on 2020-12-19 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0006_auto_20201219_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
