# Generated by Django 2.2 on 2021-01-07 12:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0009_auto_20210107_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='user_likes', through='tweets.TweetLike', to=settings.AUTH_USER_MODEL),
        ),
    ]
